version: '3.8'

services:
  linkmoa-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILE=${SPRING_PROFILE}
    container_name: linkmoa-server
    env_file:
      - ${ENV_FILE}  # 환경 변수 파일 설정
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}   # Spring Boot 포트 매핑
    restart: always

volumes:
  linkmoa-database: