spring:
  application:
    name: linkmoa-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope: profile, email

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    bearer-type: Bearer
    access-token-expiration: 2592000000 # 30일 (한 달)  #3600000 : 1시간
    refresh-token-expiration: 1209600000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    enable:
      jvm: true
      process: true
      http: true
      system: true
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 히스토그램 활성화