package com.linkmoa.source.global.constant;

public enum CommandType {
	VIEW,
	EDIT,
	CREATE,
	DIRECTORY_TRANSMISSION,
	SHARED_PAGE_INVITATION,
	SHARED_PAGE_DELETION,
	SHARED_PAGE_USER_REMOVAL,
	SHARED_PAGE_LEAVE,
	SHARED_PAGE_PERMISSION_CHANGE
}

